language: node_js
node_js:
  - '10'
cache:
  npm: true
  directories:
    - node_modules
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local_dir: dist
  skip_cleanup: true
  region: 'ap-southeast-1'
  on:
    branch: master
